<h1>Algoritmo de entrenamiento de perceptrón</h1>
<h4>Integrantes: Javier Eduardo Gutierrez Serrano - Wilder Ofrey Bello Herrera</h4>

In [2]:
import numpy as np

In [3]:
# Numero de elementos en el dataset
N = 10
x_i = list(range(1,N+1))
#print(x_i)
# 1. Inicializar aleatoriamente los parametros(pesos) w_i
W = np.random.randint(N, size=(N, N))
#print(W)
# 2. Definir el numero maximo de iteraciones
k = 2
def FA(connection):
    FA = list()
    for con in connection:
        if con < 0:
            FA.append(0)
        else:
            FA.append(1)
    return FA
error = 1
while (error != 0 or k == 0):
    # 3. Calcular la suma net
    net = list()
    i = 0
    for w_i in W:
        suma = 0
        for j in w_i:
            suma += j*x_i[i]
        net.append(suma)
        i += 1
    # 4. Calcule el calor de salida Y
    y = FA(net)
    # 5. Calcule el error y_barra - y
    errores = list()
    i = 0
    for y_element in y:
        y_barra = 0
        error = y_barra - y_element
        errores.append(error)
    
    for error in errores:
        if error != 0:
            W[k+1] = W[k] + error*x_i[i]
            print(W)
        else: 
            i += 1
    if i == len(errores):
        break
    k -= 1

[[5 1 7 4 1 7 2 8 7 2]
 [0 6 7 1 8 2 2 2 7 0]
 [8 2 5 6 5 7 5 2 4 1]
 [7 1 4 5 4 6 4 1 3 0]
 [5 8 1 5 4 8 8 4 7 6]
 [0 0 1 0 3 9 9 7 5 2]
 [5 8 5 1 1 8 3 8 7 8]
 [7 1 5 2 9 3 8 1 7 0]
 [2 9 3 0 7 4 9 4 2 6]
 [0 1 5 2 6 6 3 2 1 6]]
[[5 1 7 4 1 7 2 8 7 2]
 [0 6 7 1 8 2 2 2 7 0]
 [8 2 5 6 5 7 5 2 4 1]
 [7 1 4 5 4 6 4 1 3 0]
 [5 8 1 5 4 8 8 4 7 6]
 [0 0 1 0 3 9 9 7 5 2]
 [5 8 5 1 1 8 3 8 7 8]
 [7 1 5 2 9 3 8 1 7 0]
 [2 9 3 0 7 4 9 4 2 6]
 [0 1 5 2 6 6 3 2 1 6]]
[[5 1 7 4 1 7 2 8 7 2]
 [0 6 7 1 8 2 2 2 7 0]
 [8 2 5 6 5 7 5 2 4 1]
 [7 1 4 5 4 6 4 1 3 0]
 [5 8 1 5 4 8 8 4 7 6]
 [0 0 1 0 3 9 9 7 5 2]
 [5 8 5 1 1 8 3 8 7 8]
 [7 1 5 2 9 3 8 1 7 0]
 [2 9 3 0 7 4 9 4 2 6]
 [0 1 5 2 6 6 3 2 1 6]]
[[5 1 7 4 1 7 2 8 7 2]
 [0 6 7 1 8 2 2 2 7 0]
 [8 2 5 6 5 7 5 2 4 1]
 [7 1 4 5 4 6 4 1 3 0]
 [5 8 1 5 4 8 8 4 7 6]
 [0 0 1 0 3 9 9 7 5 2]
 [5 8 5 1 1 8 3 8 7 8]
 [7 1 5 2 9 3 8 1 7 0]
 [2 9 3 0 7 4 9 4 2 6]
 [0 1 5 2 6 6 3 2 1 6]]
[[5 1 7 4 1 7 2 8 7 2]
 [0 6 7 1 8 2 2 2 7 0]
 [8 2 5 6 5 7 5 2 4 1]
 [7 1 4

IndexError: index -11 is out of bounds for axis 0 with size 10