In [1]:
import numpy as np

np.random.seed(42)

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
# Tamaño
N_input = 5
N_hidden_1 = 4
N_hidden_2 = 3
N_out = 2

In [13]:
# Pesos
W_input_to_hidden_1 = np.random.normal(0, 0.1, (N_input, N_hidden_1))
#print(W_input_to_hidden_1)

W_hidden_1_to_hidden_2 = np.random.normal(0, 0.1, (N_hidden_1, N_hidden_2))
#print(W_hidden_1_to_hidden_2)

W_hidden_2_to_out = np.random.normal(0, 0.1, (N_hidden_2, N_out))
#print(W_hidden_2_to_out)

X = np.random.randn(N_input)
X[0] = 1
print(X)

[ 1.         -0.60021688  0.06980208 -0.3853136   0.11351735]


In [14]:
# Salida de la red
input_to_hidden_1 = np.dot(X, W_input_to_hidden_1)
out_of_hidden_1 = sigmoid(input_to_hidden_1)
print(out_of_hidden_1)

input_to_hidden_2 = np.dot(out_of_hidden_1, W_hidden_1_to_hidden_2)
out_of_hidden_2 = sigmoid(input_to_hidden_2)
print(out_of_hidden_2)

out_of_hidden_2_to_out = np.dot(out_of_hidden_2, W_hidden_2_to_out)
out_of_out = sigmoid(out_of_hidden_2_to_out)
print(out_of_out)

[0.48288969 0.49696391 0.48443679 0.49090475]
[0.48401339 0.44875007 0.49745733]
[0.51827452 0.48848934]
